name: RainbowArmor
main: de.eintosti.rainbowarmor.RainbowArmor
version: "2.3"
author: einTosti

commands:
  RainbowArmor:
      aliases: [ra]
      description: Wow, faaaancy!
      usage: /<command>

permissions:
    rainbowArmor.use:
      default: op
    rainbowArmor.reloadConfig:
      default: op